config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#landing'

  resources :croix
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/croix.rb
class Croix < ApplicationRecord
  belongs_to :discordid

  def findbyid

  end
end

app/models/discordid.rb
class Discordid < ApplicationRecord
  has_many :croixes

  def count
    croixes.pluck.sum
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :discordid
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/croix_controller.rb
class CroixController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]
  def index

  end

  def new
    @new_croix = Croix.new  #no use yet
    @discord_users = Discordid.all

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[landing]
  def landing

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/croix_helper.rb
module CroixHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/croix/index.html.erb
<div class="pillori-page">
  <div class="title">
    <h1>Voici le pillori planter dans le bac à sable</h1>
    <p>Si vous avez perdu pied, laché votre grain de folie afin que le tas de sable monte</p>
  </div>
  <div>
    <%= link_to "Ajout de croix (visible par le donneur de croix)", new_croix_path %>
  </div>
  <div class="record">
    <div class="month">
      <h2>Records du mois :</h2>
      <h4>Plus grand nombre de croix :</h4>
      <h4>Plus grand montant versé :</h4>
      <h4>Plus grand nombre en une journée :</h4>
      <h4>Moyenne de croix par jour : 7</h4>

    </div>

    <div classs="alltime">
      <h2>Records de tous les temps</h2>
      <h4>Plus grand nombre de croix :</h4>
      <h4>Plus grand montant versé :</h4>
      <h4>Plus grand nombre en une journée : Aragon     12</h4>
      <h4>Moyenne de croix par jour : 7</h4>

    </div>
  </div>

  <div class="succes">
    <h2>Les hauts faits de la croix</h2>
    <h4>Le Sage :</h4>
    <P>(Joueur étant venu régulièrement sur le vocal, et n'ayant pas reçu de croix)</p>
    <h4>Le Mécène :</h4>
    <P>(A payé un million de pièces d'or pour ses croix)</p>
    <h4>Poupou :</h4>
    <P>(A fini second)</p>
    <h4>Le Grognard :</h4>
    <P>(A été débouté par la majorité 10 fois après avoir contesté une croix)</p>
    <h4>L'Avocat :</h4>
    <P>(A réussi 10 fois à faire invalider une croix)</p>
    <h4>L'Agent (Fayot) :</h4>
    <P>(A fait rajouter dix croix à d'autres joueurs)</p>
    <h4>Chevalier de la croix de fer : 07/11/2021 Chalomar</h4>
    <P>(A organisé un événement durant lequel 10 croix ont été distribuées)</p>
  </div>


</div>
<%#
user_signed_in?
# => true / false
current_user
# => User instance / nil %>

app/views/croix/new.html.erb
<div class="newcroix-page">
  <div class="title">
    <h1>Voici ton nouveau stylo</h1>
    <p>Si tu vois un grain de sable tomber, clique sur le pseudo de celui qui l'a laissé s'échapper!</p>
  </div>
  <div>
    <%= link_to "Retour au résumé", croix_index_path %>
  </div>
  <div>
    <% @discord_users.each do |user| %>
    <%= user.gameid %>
    <% end %>
  </div>

app/views/home/landing.html.erb
<div class="common-page">
  <div class="title">
    <h1>Bienvenue</h1>
    <p>Vous étes arrivé(e) à la croisé des chemins</p>
  </div>
  <div class="content">
    <div id="pillule-bleu">
      <%= link_to "Allez sur le site officiel", "http://www.akairaion.net/", :target => "_blank" %>
    </div>
    <div id="pillule-rouge">
      <%= link_to "Continuer vers le bac à sable", croix_index_url %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AkaiRaion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render 'shared/footer' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/shared/_footer.html.erb
pied de page